apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: pipelines-spark-yaml
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/managed-by: Helm
  name: pipelines-spark-yaml
  namespace: test
data:
  pipelines-spark.yaml: |
    inputPath: hdfs://gbif-hdfs/data/ingest
    outputPath: hdfs://gbif-hdfs/data/ingest_spark
    zkConnectionString: c5n7.gbif-test.org:31706,c5n9.gbif-test.org:31706,c6n8.gbif-test.org:31706
    gbifApi:
      wsUrl: https://api.gbif-test.org/v1/
    nameUsageMatchingService:
      checklistKeys:
        - d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
      ws:
        numOfKeyBuckets: 10
        zkConnectionString: c5n7.gbif-test.org:31706,c5n9.gbif-test.org:31706,c6n8.gbif-test.org:31706
        tableName: test_name_usage_kv
        api:
          wsUrl: https://api.gbif-test.org/
        hbaseZnode: /znode-93f9cdb5-d146-46da-9f80-e8546468b0fe/hbase          
    vocabularyService:
      wsUrl: https://api.gbif.org/v1/
    grscicollLookup:
      numOfKeyBuckets: 9
      zkConnectionString: c5n7.gbif-test.org:31706,c5n9.gbif-test.org:31706,c6n8.gbif-test.org:31706
      tableName: test_grscicoll_lookup_kv
      api:
        wsUrl: https://api.gbif-test.org/v1/
      hbaseZnode: /znode-93f9cdb5-d146-46da-9f80-e8546468b0fe/hbase  
    geocode:
      numOfKeyBuckets: 25
      zkConnectionString: c5n7.gbif-test.org:31706,c5n9.gbif-test.org:31706,c6n8.gbif-test.org:31706
      tableName: test_geocode_kv
      wsCacheSizeMb: 128
      loaderRetryConfig:
        maxAttempts: 10      
      api:
        wsUrl: https://api.gbif-test.org/v1/
      hbaseZnode: /znode-93f9cdb5-d146-46da-9f80-e8546468b0fe/hbase  
    imageCachePath: /bitmap/bitmap.png
    content:
      esHosts:
        - http://cms-search.gbif-dev.org:9200/
    amplification:
      wsUrl: http://blast.gbif-dev.org
    keygen:
      occurrenceTable: dev_occurrence
      counterTable: dev_occurrence_counter
      lookupTable: dev_occurrence_lookup
      zkConnectionString: c5n7.gbif-test.org:31706,c5n9.gbif-test.org:31706,c6n8.gbif-test.org:31706
      hbaseZnode: /znode-93f9cdb5-d146-46da-9f80-e8546468b0fe/hbase